### ISSUE TITLE
Error while running the code

### ISSUE THREAD

**Issue by starkgg123** [techaliceblue/AntV2Python#1]
Invalid Session request : Ok
Create Session request  : Ok
Opened connection
Traceback (most recent call last):
  File "C:\Users\parva\Downloads\webs\AntV2Python-main\main.py", line 70, in <module>
    rel.dispatch()
  File "C:\Users\parva\anaconda3\lib\site-packages\rel\rel.py", line 205, in dispatch
    registrar.dispatch()
  File "C:\Users\parva\anaconda3\lib\site-packages\rel\registrar.py", line 72, in dispatch
    if not self.loop():
  File "C:\Users\parva\anaconda3\lib\site-packages\rel\registrar.py", line 81, in loop
    e = self.check_events()
  File "C:\Users\parva\anaconda3\lib\site-packages\rel\registrar.py", line 195, in check_events
    self.callback('read', fd)
  File "C:\Users\parva\anaconda3\lib\site-packages\rel\registrar.py", line 125, in callback
    self.events[etype][fd].callback()
  File "C:\Users\parva\anaconda3\lib\site-packages\rel\listener.py", line 108, in callback
    if not self.cb(*self.args) and not self.persist and self.active:
TypeError: read() takes 0 positional arguments but 1 was given

**Comment by rahul1906** [comment]
Just upgrade to the latest websocket package(1.4.2). This solved the issue for me.
`pip install websocket-client --upgrade`
